config/routes.rb
Rails.application.routes.draw do
  root 'businesses#index'

  resources :businesses do
    collection do
      get 'autocomplete'
      get 'result'
    end
  end

  resources :users

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :user

  validates_uniqueness_of :place_id, allow_blank: true

  scope :business_search, ->(q) { order(:address).where("address ILIKE ?", "%#{q}%").limit(20) }

  class << self
    def create_business(place, user_id)
      create(
          business_name: place.name,
          address: place.formatted_address,
          city: place.city,
          state: place.region,
          zip: place.postal_code,
          place_id: place.place_id,
          user_id: user_id,
      )
    end

    def place(place_id)
      where(place_id: place_id).first
    end

    def claim_business(id, user_id)
      update(id, {user_id: user_id})
    end

    def place_json(desc, logo, id, place_id, disabled)
      {
          label: desc,
          logo: logo,
          id: id,
          place_id: place_id,
          disabled: disabled
      }
    end
  end

  def main_address
    [address, city, state, zip].compact.join(', ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :businesses, dependent: :nullify

  validates :email, :last_name,  :first_name, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize

  protect_from_forgery with: :exception

  protected

  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please log in"
    end
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = current_user.businesses
  end

  def create
    redirect_to '/', notice: "Empty place_id and id" and return  if (params[:id].empty? && params[:place_id].empty?)

    if params[:id].empty?
      Business.create_business(google_autocomplete.spot(params[:place_id], details: true), session[:user_id])
    else
      Business.claim_business(params[:id], session[:user_id])
    end

    redirect_to '/'
  end

  def autocomplete
    render json: send(params[:type])
  end

  private

  def google_autocomplete
    GooglePlaces::Client.new(ENV['GOOGLE_API_KEY'])
  end

  def all_data
    database_data + google_data
  end

  def type_establishment
    google_autocomplete.predictions_by_input(params[:q], types: 'establishment')
  end

  def google_data
    type_establishment.reduce([]) do |arr, i| p = Business.place(i.place_id); arr <<
        Business.place_json(i.description, 'fa fa-google', p.try(:id), i.place_id, p.try(:user_id))
    end
  end

  def database_data
    Business.business_search(params[:q]).reduce([]) do |arr, i| arr <<
        Business.place_json(i.main_address, 'fa fa-building', i.id, nil, i.user_id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
    signed_in?
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to '/'
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to '/', notice: "Logged out"
  end

  private

  def signed_in?
    redirect_to '/', notice: "You are already logged in" unless session[:user_id].nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize

  def index
    @users = User.order(:name)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path,
                                  notice: "User #{@user.first_name} was successfully created." }
        format.json { render action: 'show',
                             status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url,
                                  notice: "User #{@user.first_name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_signed_in?
    !session[:user_id].nil?
  end
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing Businesses</h1>
<p id="notice"><%= notice %></p>
<%= form_tag({:controller => "/businesses", :action => "create"}, :id => 'business_form', method: "post") do %>
  <div class="form-group">
    <%= radio_button_tag('type_search', 'all_data', true, id: 'all') %>
    <%= label_tag :all %>
    <%= radio_button_tag('type_search', 'google_data', false, id: 'google') %>
    <%= label_tag :google %>
    <%= radio_button_tag('type_search', 'database_data', false, id: 'database') %>
    <%= label_tag :database %>
  </div>
  <div class="form-group col-sm-11">
    <%= text_field_tag(:q, nil, placeholder: 'Search business', id: 'searchInput', class: 'form-control') %>
    <%= hidden_field_tag(:place_id, '') %>
    <%= hidden_field_tag(:id, '') %>
  </div>
  <div class="form-group col-sm-1">
    <%= submit_tag 'Claim Business', class: 'btn btn-primary', id: 'submit_btn', disabled: true %>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <% @businesses.each do |business| %>
    <p><i class="ui-red fa <%= business.place_id.nil? ? 'fa fa-building' : 'fa fa-google' %>"></i> <%= business.business_name %> <%= business.address %></p>
    <% end %>
  </div>
</div>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business name:</strong>
  <%= @business.business_name %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GooglePlacesSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Businesses</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/">Home</a></li>
        <li><%= user_signed_in? ? link_to('Logout', logout_path, method: :delete) : link_to('Sign_in', login_path) %></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <div class="starter-template">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Enter User Details</h4>

  <div class="form-group">
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :first_name, 'First name:' %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, 'Last name:' %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Confirm:' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= f.submit  'Create user', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<!-- START_HIGHLIGHT -->
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>